"""
build_walkable_scene.py
=======================
Blender Python pipeline script for converting a 2D-floor-plan-derived
3MF house mesh (generated by OpenSCAD) into a fully configured, walkable
Blender scene.

Usage (from the command line):
    blender -b -P build_walkable_scene.py -- house_model.3mf interactive_house.blend

Arguments after '--' are parsed by this script:
    argv[0]  ->  Path to the input .3mf file
    argv[1]  ->  Path for the output .blend file

Pipeline Steps:
    1. Scene Initialization   - Clear default objects, parse CLI args.
    2. Mesh Import            - Parse the .3mf natively (stdlib), write a
                                temp OBJ, import via wm.obj_import, then
                                bake per-face colors into a vertex color
                                attribute.
    3. Vertex Color Material  - PBR Principled BSDF driven by vertex colors.
    4. Sky & Lighting         - Cycles engine + Nishita Sky for daylight.
    5. First-Person Camera    - "Player_Camera" at eye-level inside the mesh.
    6. Save & Exit            - Write the .blend file and quit cleanly.

Note on Blender 5.2 compatibility:
    Blender 5.2 no longer bundles the io_scene_3mf add-on, so
    bpy.ops.import_mesh.threemf does not exist.  A .3mf file is a ZIP
    archive containing XML geometry (3D Manufacturing Format spec).  We
    parse it with stdlib zipfile + xml.etree.ElementTree, convert to a
    temporary .obj + .mtl, import with bpy.ops.wm.obj_import, and then
    bake the per-face material colors into a Blender vertex color layer.
"""

import sys
import math
import os
import tempfile
import zipfile
import xml.etree.ElementTree as ET
import bpy


# =============================================================================
# STEP 0 - Utility helpers
# =============================================================================

def log(msg: str) -> None:
    """Simple timestamped logger so progress is visible in the Blender console."""
    print(f"[build_walkable_scene] {msg}", flush=True)


def deselect_all() -> None:
    """Deselect every object in the scene."""
    bpy.ops.object.select_all(action='DESELECT')


def select_obj(obj: bpy.types.Object) -> None:
    """Select *obj* and make it the active object."""
    deselect_all()
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj


# =============================================================================
# STEP 1 - Scene Initialization
# =============================================================================

def parse_cli_args() -> tuple:
    """
    Parse the input .3mf and output .blend paths from the command line.

    Supports two invocation modes:

    1. Via Blender (canonical):
            blender -b -P build_walkable_scene.py -- house.3mf out.blend
       Blender inserts a '--' separator; we slice everything after it.

    2. Direct Python (development / bpy-pip):
            python build_walkable_scene.py house.3mf out.blend
       No '--' separator; we treat sys.argv[1] and sys.argv[2] directly.

    Returns:
        (input_3mf_path, output_blend_path) as a tuple of strings.
    """
    # --- Mode 1: Blender wrapper (has '--' separator) -----------------------
    if "--" in sys.argv:
        separator_index = sys.argv.index("--")
        script_args = sys.argv[separator_index + 1:]
        mode = "blender-wrapped"

    # --- Mode 2: Direct Python invocation (no '--') -------------------------
    else:
        # sys.argv[0] is the script name; [1] and [2] are the user args.
        script_args = sys.argv[1:]
        mode = "direct-python"

    if len(script_args) < 2:
        raise SystemExit(
            "ERROR: Expected 2 path arguments.\n\n"
            "  Via Blender :\n"
            "    blender -b -P build_walkable_scene.py -- "
            "house_model.3mf interactive_house.blend\n\n"
            "  Direct Python:\n"
            "    python build_walkable_scene.py "
            "house_model.3mf interactive_house.blend\n\n"
            f"Received ({mode}): {script_args}"
        )

    input_path  = script_args[0]
    output_path = script_args[1]
    log(f"Invocation mode : {mode}")
    log(f"Input  .3mf     : {input_path}")
    log(f"Output .blend   : {output_path}")
    return input_path, output_path


def clear_default_scene() -> None:
    """
    Remove every object that Blender places in a new scene by default
    (Cube, Camera, Light) so we start with a completely empty slate.
    Also purge orphaned data-blocks to keep the file clean.
    """
    log("Clearing default scene objects ...")

    # Iterate over a *copy* because we modify bpy.data.objects in-place.
    for obj in list(bpy.data.objects):
        bpy.data.objects.remove(obj, do_unlink=True)

    # Purge orphaned mesh, light, and camera data-blocks.
    for mesh in list(bpy.data.meshes):
        bpy.data.meshes.remove(mesh)
    for light in list(bpy.data.lights):
        bpy.data.lights.remove(light)
    for camera in list(bpy.data.cameras):
        bpy.data.cameras.remove(camera)

    log("Default scene cleared.")


# =============================================================================
# STEP 2 - Mesh Import & Geometry Optimization
# =============================================================================

# =============================================================================
# 3MF NATIVE PARSER  (stdlib only — no Blender add-on required)
# =============================================================================

# The 3MF spec defines geometry inside a ZIP archive.  The main model file
# is typically "3D/3dmodel.model" and uses the namespace:
_3MF_NS = "http://schemas.microsoft.com/3dmanufacturing/core/2015/02"


def _parse_3mf_to_obj(filepath: str, obj_path: str, mtl_path: str) -> None:
    """
    Parse a .3mf file and write an equivalent Wavefront OBJ + MTL pair.

    3MF geometry lives in a ZIP archive under "3D/3dmodel.model".
    Each <object> element contains:
        <vertices>  ->  <vertex x y z>  entries.
        <triangles> ->  <triangle v1 v2 v3 pid p1> entries.
    The optional 'pid' / 'p1' attributes reference a <basematerials>
    palette which stores the RGB colors assigned via OpenSCAD color().

    We convert each material in the palette to a named MTL entry, then
    write per-face 'usemtl' directives so that after import Blender gives
    each face the correct color.  We then bake those per-face material
    colors into a vertex color attribute.

    Args:
        filepath : Path to the source .3mf file.
        obj_path : Destination path for the .obj text file.
        mtl_path : Destination path for the .mtl text file.
    """
    log(f"Parsing .3mf with stdlib XML parser: {filepath}")

    mtl_filename = os.path.basename(mtl_path)

    with zipfile.ZipFile(filepath, 'r') as zf:
        # Locate the primary model file (spec default: "3D/3dmodel.model").
        model_entry = None
        for name in zf.namelist():
            if name.lower().endswith(".model"):
                model_entry = name
                break
        if model_entry is None:
            raise RuntimeError(
                f"No .model entry found inside '{filepath}'. "
                "Is this a valid .3mf file?"
            )
        log(f"Found model entry: {model_entry}")
        model_xml = zf.read(model_entry)

    root = ET.fromstring(model_xml)
    ns   = {'m': _3MF_NS}

    # --- Parse material palettes (basematerials) ----------------------------
    # Maps palette_id -> {material_index -> (r, g, b)}  (floats 0-1)
    palettes: dict[str, dict[int, tuple]] = {}
    for bm in root.findall('.//m:basematerials', ns):
        pid = bm.get('id', '0')
        colors: dict[int, tuple] = {}
        for idx, base in enumerate(bm.findall('m:base', ns)):
            raw = base.get('displaycolor', '#FFFFFF')
            # displaycolor is a CSS hex string: #RRGGBB or #RRGGBBAA
            raw = raw.lstrip('#')
            r = int(raw[0:2], 16) / 255.0
            g = int(raw[2:4], 16) / 255.0
            b = int(raw[4:6], 16) / 255.0
            colors[idx] = (r, g, b)
        palettes[pid] = colors
        log(f"Palette '{pid}': {len(colors)} color(s).")

    # --- Build MTL file from palette colors ----------------------------------
    # mat name: "mat_{pid}_{index}"  e.g. "mat_1_0"
    mat_entries: dict[str, tuple] = {}  # name -> (r, g, b)
    for pid, colors in palettes.items():
        for idx, rgb in colors.items():
            mat_name = f"mat_{pid}_{idx}"
            mat_entries[mat_name] = rgb

    # Fallback white material used when no palette reference is present.
    mat_entries['mat_default'] = (0.8, 0.8, 0.8)

    with open(mtl_path, 'w') as mf:
        mf.write(f"# Generated by build_walkable_scene.py\n")
        for mname, (r, g, b) in mat_entries.items():
            mf.write(f"\nnewmtl {mname}\n")
            mf.write(f"Ka {r:.6f} {g:.6f} {b:.6f}\n")   # ambient
            mf.write(f"Kd {r:.6f} {g:.6f} {b:.6f}\n")   # diffuse
            mf.write(f"Ks 0.1 0.1 0.1\n")                # specular
            mf.write(f"Ns 10.0\n")                        # shininess
            mf.write(f"d 1.0\n")                          # opacity

    log(f"MTL written: {mtl_path} ({len(mat_entries)} materials)")

    # --- Parse geometry and write OBJ ----------------------------------------
    with open(obj_path, 'w') as of:
        of.write(f"# Generated by build_walkable_scene.py\n")
        of.write(f"mtllib {mtl_filename}\n\n")

        global_vertex_offset = 0  # OBJ vertex indices are 1-based and global.

        for obj_el in root.findall('.//m:object', ns):
            obj_id   = obj_el.get('id', 'unknown')
            obj_name = obj_el.get('name', f'object_{obj_id}').replace(' ', '_')
            mesh_el  = obj_el.find('m:mesh', ns)
            if mesh_el is None:
                continue

            of.write(f"o {obj_name}\n")

            # --- Vertices ---
            verts_el = mesh_el.find('m:vertices', ns)
            vertices = []
            if verts_el is not None:
                for v in verts_el.findall('m:vertex', ns):
                    x, y, z = float(v.get('x', 0)), float(v.get('y', 0)), float(v.get('z', 0))
                    vertices.append((x, y, z))
                    of.write(f"v {x:.8f} {y:.8f} {z:.8f}\n")

            # --- Triangles --------------------------------------------------
            # Group consecutive triangles that share the same material together
            # so we minimise 'usemtl' line changes.
            tris_el = mesh_el.find('m:triangles', ns)
            if tris_el is None:
                global_vertex_offset += len(vertices)
                continue

            triangles = tris_el.findall('m:triangle', ns)

            # Determine per-triangle material name.
            current_mat  = None
            base_offset  = global_vertex_offset  # offset for this object's verts

            of.write(f"usemtl mat_default\n")  # prime with a default
            current_mat = 'mat_default'

            for tri in triangles:
                v1 = int(tri.get('v1')) + base_offset + 1  # OBJ is 1-indexed
                v2 = int(tri.get('v2')) + base_offset + 1
                v3 = int(tri.get('v3')) + base_offset + 1

                pid = tri.get('pid')
                p1  = tri.get('p1')
                if pid is not None and p1 is not None:
                    mat_name = f"mat_{pid}_{p1}"
                else:
                    mat_name = 'mat_default'

                if mat_name not in mat_entries:
                    mat_name = 'mat_default'

                if mat_name != current_mat:
                    of.write(f"usemtl {mat_name}\n")
                    current_mat = mat_name

                of.write(f"f {v1} {v2} {v3}\n")

            global_vertex_offset += len(vertices)
            of.write("\n")

    log(f"OBJ written: {obj_path} ({global_vertex_offset} vertices total)")


def _bake_material_colors_to_vertex_color(obj: bpy.types.Object) -> None:
    """
    After importing an OBJ, Blender assigns a separate material slot to
    each 'usemtl' group.  This function reads the Kd (diffuse) color from
    each material and bakes it into a per-loop vertex color attribute so
    the rest of the pipeline (which expects vertex colors) works correctly.

    Steps:
        1. Create a new Color Attribute layer named 'Col'.
        2. For each face, look up the material in its slot, read its
           Kd-equivalent node color (or diffuse_color), and write that
           color to all loops of the face.
    """
    log("Baking per-face material colors into vertex color attribute ...")

    mesh = obj.data

    # Create the color attribute (per-loop, BYTE_COLOR for efficiency).
    if 'Col' in mesh.color_attributes:
        mesh.color_attributes.remove(mesh.color_attributes['Col'])
    col_attr = mesh.color_attributes.new(
        name='Col', type='BYTE_COLOR', domain='CORNER'
    )
    mesh.color_attributes.active_color = col_attr

    # Build a lookup: material_index -> (r, g, b)
    mat_color_map: dict[int, tuple] = {}
    for mat_idx, mat in enumerate(obj.data.materials):
        if mat is None:
            mat_color_map[mat_idx] = (0.8, 0.8, 0.8)
            continue
        # Try to read Kd from the Principled BSDF Base Color if nodes are on.
        if mat.use_nodes:
            bsdf = mat.node_tree.nodes.get('Principled BSDF')
            if bsdf:
                bc = bsdf.inputs['Base Color'].default_value
                mat_color_map[mat_idx] = (bc[0], bc[1], bc[2])
                continue
        # Fallback: use mat.diffuse_color.
        dc = mat.diffuse_color
        mat_color_map[mat_idx] = (dc[0], dc[1], dc[2])

    # Paint every loop with the color of its face's material.
    color_data = col_attr.data
    for poly in mesh.polygons:
        rgb = mat_color_map.get(poly.material_index, (0.8, 0.8, 0.8))
        for loop_idx in poly.loop_indices:
            cd = color_data[loop_idx]
            cd.color = (rgb[0], rgb[1], rgb[2], 1.0)

    log(f"Vertex colors baked across {len(mesh.polygons)} faces.")


def import_3mf(filepath: str) -> bpy.types.Object:
    """
    Import a .3mf house mesh into Blender 5.2.

    Blender 5.2 removed the io_scene_3mf add-on, so we use a two-stage
    approach that relies only on operators that exist in 5.2:

        Stage A – stdlib parse:
            Read the .3mf (a ZIP of XML) with Python's zipfile and
            xml.etree.ElementTree modules.  Extract vertices, triangles,
            and basematerial color palettes.  Write a temporary .obj + .mtl
            pair that encodes the colors as named materials.

        Stage B – Blender OBJ import:
            Call bpy.ops.wm.obj_import on the temp .obj file.
            Join any multiple resulting objects into one 'House_Mesh'.
            Bake the per-face material colors into a 'Col' vertex color
            attribute so the rest of the pipeline can read them uniformly.

    Args:
        filepath: Absolute or relative path to the .3mf file.

    Returns:
        The imported (and merged) mesh object named 'House_Mesh'.
    """
    log(f"Importing .3mf: {filepath} ...")

    # Resolve to an absolute path so temp files land next to it cleanly.
    abs_path = os.path.abspath(filepath)

    # Create temp OBJ and MTL paths alongside the source file.
    tmp_dir  = tempfile.mkdtemp()
    obj_path = os.path.join(tmp_dir, "house_temp.obj")
    mtl_path = os.path.join(tmp_dir, "house_temp.mtl")

    # --- Stage A: parse 3MF -> OBJ/MTL -------------------------------------
    _parse_3mf_to_obj(abs_path, obj_path, mtl_path)

    # --- Stage B: import OBJ into Blender ----------------------------------
    pre_import_names = {obj.name for obj in bpy.data.objects}

    # bpy.ops.wm.obj_import exists in Blender 4.0+ (replaces import_scene.obj).
    bpy.ops.wm.obj_import(
        filepath=obj_path,
        forward_axis='Y',    # 3MF Y-forward convention
        up_axis='Z',
    )

    new_objects = [
        obj for obj in bpy.data.objects
        if obj.name not in pre_import_names and obj.type == 'MESH'
    ]

    if not new_objects:
        raise RuntimeError(
            "No mesh objects were created after importing the converted OBJ. "
            f"Check that '{obj_path}' contains valid geometry."
        )

    log(f"OBJ import created {len(new_objects)} mesh object(s).")

    # --- Merge all objects --------------------------------------------------
    deselect_all()
    for obj in new_objects:
        obj.select_set(True)
    bpy.context.view_layer.objects.active = new_objects[-1]

    if len(new_objects) > 1:
        log("Joining imported meshes into a single object ...")
        bpy.ops.object.join()

    house_obj = bpy.context.view_layer.objects.active
    house_obj.name = "House_Mesh"

    # --- Bake material colors -> vertex color attribute ---------------------
    _bake_material_colors_to_vertex_color(house_obj)

    # --- Clean up temp files ------------------------------------------------
    try:
        os.remove(obj_path)
        os.remove(mtl_path)
        os.rmdir(tmp_dir)
        log("Temporary OBJ/MTL files removed.")
    except OSError as e:
        log(f"WARNING: Could not remove temp files: {e}")

    log(f"House mesh ready: '{house_obj.name}'")
    return house_obj


def apply_smooth_shading(obj: bpy.types.Object) -> None:
    """
    Apply Shade Smooth to the mesh and add an Edge Split modifier.

    Why Edge Split instead of the old Auto Smooth mesh property?
    - Blender 4.1+ removed 'mesh.use_auto_smooth' from the mesh data API.
    - Edge Split with a 30-degree threshold is the cross-version compatible
      approach: it keeps 90-degree architectural wall corners crisp while
      smoothing curved surfaces like arches or furniture.

    Threshold: 30 degrees
        - Edges whose dihedral angle exceeds 30 deg are split (rendered hard).
        - Right-angle walls (90 deg) are well above the threshold -> hard.
        - Gentle curves (< 30 deg between faces) -> smooth shading.
    """
    log("Applying shade-smooth + Edge Split modifier ...")

    select_obj(obj)

    # Mark all faces as smooth-shaded (no per-face hard/flat shading).
    bpy.ops.object.shade_smooth()

    # Add the Edge Split modifier.
    edge_split_mod = obj.modifiers.new(name="Edge_Split_Arch", type='EDGE_SPLIT')

    # 30 degrees in radians.
    edge_split_mod.split_angle   = math.radians(30)
    edge_split_mod.use_edge_angle = True   # Split by angle threshold.
    edge_split_mod.use_edge_sharp = False  # Ignore manually-marked sharp edges.

    log("Shade smooth + Edge Split (30 deg threshold) applied.")


# =============================================================================
# STEP 3 - Vertex Color PBR Material Setup
# =============================================================================

def get_vertex_color_layer_name(obj: bpy.types.Object) -> str:
    """
    Retrieve the name of the active vertex color / color attribute layer
    on the mesh.

    API compatibility:
        Blender 3.2+  -> mesh.color_attributes  (preferred)
        Blender < 3.2 -> mesh.vertex_colors      (legacy)

    Returns:
        Name string of the active color layer, or 'Col' as a safe fallback.
    """
    mesh = obj.data

    # Modern Blender 3.2+ path.
    if hasattr(mesh, "color_attributes") and len(mesh.color_attributes) > 0:
        active_attr = mesh.color_attributes.active_color
        layer_name  = active_attr.name if active_attr else mesh.color_attributes[0].name
        log(f"Found color_attributes layer: '{layer_name}'")
        return layer_name

    # Legacy path (Blender < 3.2).
    if hasattr(mesh, "vertex_colors") and len(mesh.vertex_colors) > 0:
        layer_name = mesh.vertex_colors.active.name
        log(f"Found vertex_colors layer: '{layer_name}'")
        return layer_name

    log("WARNING: No vertex color layer found. Falling back to 'Col'.")
    return "Col"


def build_vertex_color_material(obj: bpy.types.Object) -> bpy.types.Material:
    """
    Build a realistic PBR material whose Base Color is driven entirely by
    the mesh's vertex color / color attribute layer.

    Node graph:
        [ShaderNodeVertexColor]
              |
              | Color
              v
        [Principled BSDF]  (Roughness=0.8, Specular=0.1)
              |
              | BSDF
              v
        [Material Output]

    The Principled BSDF settings produce a matte, architectural-surface look:
        Roughness 0.8  -> diffuse / slightly rough surface (concrete, drywall).
        Specular  0.1  -> nearly non-reflective (avoids plastic-like shine).

    Returns:
        The created bpy.types.Material.
    """
    log("Building vertex-color PBR material ...")

    mat = bpy.data.materials.new(name="House_VertexColor_PBR")
    mat.use_nodes = True

    node_tree = mat.node_tree
    nodes     = node_tree.nodes
    links     = node_tree.links

    # Start with a clean slate.
    nodes.clear()

    # --- Principled BSDF node -----------------------------------------------
    bsdf = nodes.new(type='ShaderNodeBsdfPrincipled')
    bsdf.location = (300, 300)
    bsdf.inputs["Roughness"].default_value = 0.8

    # Blender 4.0 renamed the specular input; support both names.
    if "Specular IOR Level" in bsdf.inputs:
        bsdf.inputs["Specular IOR Level"].default_value = 0.1
    elif "Specular" in bsdf.inputs:
        bsdf.inputs["Specular"].default_value = 0.1

    # --- Material Output node -----------------------------------------------
    output_node = nodes.new(type='ShaderNodeOutputMaterial')
    output_node.location = (600, 300)

    links.new(bsdf.outputs["BSDF"], output_node.inputs["Surface"])

    # --- Color Attribute / Vertex Color node --------------------------------
    color_layer_name = get_vertex_color_layer_name(obj)

    # ShaderNodeVertexColor exists in both Blender 3.x and 4.x.
    # It reads the named color attribute layer and outputs per-vertex color.
    try:
        color_node = nodes.new(type='ShaderNodeVertexColor')
        color_node.layer_name = color_layer_name
        color_node.location   = (-200, 300)
        log("Using ShaderNodeVertexColor node.")
    except Exception:
        # Ultimate fallback: generic Attribute node (works on all versions).
        color_node = nodes.new(type='ShaderNodeAttribute')
        color_node.attribute_name = color_layer_name
        color_node.attribute_type = 'GEOMETRY'
        color_node.location       = (-200, 300)
        log("Fallback: using ShaderNodeAttribute node for vertex color.")

    # Wire Color output -> Base Color input.
    links.new(color_node.outputs["Color"], bsdf.inputs["Base Color"])

    # --- Assign material to the mesh ----------------------------------------
    obj.data.materials.clear()      # Remove any auto-assigned materials.
    obj.data.materials.append(mat)

    log(f"Material '{mat.name}' assigned to '{obj.name}'.")
    return mat


# =============================================================================
# STEP 4 - Realistic Lighting & Sky
# =============================================================================

def setup_sky_and_lighting() -> None:
    """
    Switch the render engine to Cycles and add a Nishita Sky Texture as
    the World environment for physically-based outdoor daylight.

    Nishita Sky parameters used:
        sun_elevation  = 45 deg  -> mid-morning sun angle, good for shadows.
        sun_rotation   = 0 rad   -> sun located along the +Y axis.
        altitude       = 0 m     -> observer at sea level.
        air_density    = 1.0     -> standard clear atmosphere.
        dust_density   = 1.0     -> normal dust load.
        ozone_density  = 1.0     -> normal ozone layer.

    Cycles sample counts:
        128 samples (final) / 32 samples (preview) - good quality / speed
        balance for interactive use and quick test renders.
    """
    log("Setting up Cycles render engine and Nishita sky ...")

    scene = bpy.context.scene

    # --- Render engine -------------------------------------------------------
    scene.render.engine          = 'CYCLES'
    scene.cycles.samples         = 128
    scene.cycles.preview_samples = 32

    # Attempt to enable GPU rendering (CUDA for NVIDIA; silently ignores
    # errors on CPU-only machines so the script is portable everywhere).
    try:
        cycles_prefs = bpy.context.preferences.addons["cycles"].preferences
        cycles_prefs.compute_device_type = 'CUDA'
        cycles_prefs.get_devices()         # Refresh device list.
    except Exception:
        log("GPU (CUDA) not available; Cycles will use CPU.")

    # --- World / sky node graph ---------------------------------------------
    world = bpy.data.worlds.new("Sky_World")
    scene.world = world
    world.use_nodes = True

    w_nodes = world.node_tree.nodes
    w_links = world.node_tree.links
    w_nodes.clear()

    # Background node controls overall sky brightness.
    bg_node = w_nodes.new(type='ShaderNodeBackground')
    bg_node.location = (300, 300)
    bg_node.inputs["Strength"].default_value = 1.0

    # Nishita physically-based sky texture.
    # NOTE: In Blender 5.x the sky_type enum was reorganised.
    # 'NISHITA' was split into 'SINGLE_SCATTERING' and 'MULTIPLE_SCATTERING'.
    # 'MULTIPLE_SCATTERING' is the high-quality equivalent of the old Nishita.
    sky_node = w_nodes.new(type='ShaderNodeTexSky')
    sky_node.location = (-100, 300)

    # Determine the correct sky type for this Blender version.
    sky_enum_values = sky_node.bl_rna.properties['sky_type'].enum_items.keys()
    if 'NISHITA' in sky_enum_values:
        # Blender 3.x / 4.x
        sky_node.sky_type = 'NISHITA'
        sky_node.sun_elevation  = math.radians(45)   # 45 degrees above horizon
        sky_node.sun_rotation   = 0.0                # Azimuth in radians
        sky_node.altitude       = 0.0
        sky_node.air_density    = 1.0
        sky_node.dust_density   = 1.0
        sky_node.ozone_density  = 1.0
        log("Sky type: NISHITA (Blender 3.x/4.x)")
    elif 'MULTIPLE_SCATTERING' in sky_enum_values:
        # Blender 5.x — NISHITA was renamed to MULTIPLE_SCATTERING
        sky_node.sky_type = 'MULTIPLE_SCATTERING'
        # sun_elevation and sun_rotation are still available in 5.x.
        if hasattr(sky_node, 'sun_elevation'):
            sky_node.sun_elevation = math.radians(45)
        if hasattr(sky_node, 'sun_rotation'):
            sky_node.sun_rotation  = 0.0
        log("Sky type: MULTIPLE_SCATTERING (Blender 5.x equivalent of Nishita)")
    else:
        # Last-resort fallback: pick whatever the first available type is.
        first_type = list(sky_enum_values)[0]
        sky_node.sky_type = first_type
        log(f"WARNING: Neither NISHITA nor MULTIPLE_SCATTERING found. "
            f"Using '{first_type}' as fallback sky type.")

    # World Output.
    world_output = w_nodes.new(type='ShaderNodeOutputWorld')
    world_output.location = (600, 300)

    # Link: Sky -> Background -> World Output.
    w_links.new(sky_node.outputs["Color"],       bg_node.inputs["Color"])
    w_links.new(bg_node.outputs["Background"],   world_output.inputs["Surface"])

    log("Cycles engine + Nishita Sky (45 deg sun elevation) configured.")


# =============================================================================
# STEP 5 - First-Person Camera Setup
# =============================================================================

def compute_mesh_center_xy(obj: bpy.types.Object) -> tuple:
    """
    Compute the horizontal (X, Y) center of the house mesh from its
    world-space bounding box.

    The object's world matrix is applied to every vertex so the result
    is correct even if the mesh has been translated, rotated, or scaled.

    Args:
        obj: The house mesh object.

    Returns:
        (center_x, center_y) as floats in world-space metres.
    """
    world_matrix = obj.matrix_world
    mesh_data    = obj.data

    # Transform every vertex to world space.
    global_verts = [world_matrix @ v.co for v in mesh_data.vertices]

    if not global_verts:
        raise RuntimeError(
            "House mesh has no vertices - cannot compute bounding box center."
        )

    xs = [v.x for v in global_verts]
    ys = [v.y for v in global_verts]

    center_x = (min(xs) + max(xs)) / 2.0
    center_y = (min(ys) + max(ys)) / 2.0

    log(f"Mesh bounding-box XY center: ({center_x:.4f}, {center_y:.4f})")
    return center_x, center_y


def setup_first_person_camera(obj: bpy.types.Object) -> bpy.types.Object:
    """
    Create a 'Player_Camera' positioned at the center of the house at
    standard human eye height (1.6 m) and oriented to look forward.

    Camera specifications:
        Location   : (center_x, center_y, 1.6)
        Rotation   : (90 deg, 0, 0) in XYZ Euler
                     -> The camera forward vector becomes +Y (into the scene).
        Focal length: 60 mm  -> natural, non-distorted perspective.
        Clip Start : 0.05 m  -> prevents near-plane z-fighting with thin walls.
        Clip End   : 500 m   -> sufficient for any domestic floor plan.

    The camera is set as bpy.context.scene.camera so it is immediately
    active for rendering and VR walk-through previews.

    Args:
        obj: The house mesh object (used to compute XY center).

    Returns:
        The created camera object.
    """
    log("Creating first-person Player_Camera ...")

    center_x, center_y = compute_mesh_center_xy(obj)

    EYE_HEIGHT_M = 1.6  # Standard human eye level in metres.

    # --- Camera data-block --------------------------------------------------
    cam_data             = bpy.data.cameras.new(name="Player_Camera_Data")
    cam_data.lens        = 60.0    # 60 mm focal length
    cam_data.clip_start  = 0.05   # 5 cm near clip
    cam_data.clip_end    = 500.0  # 500 m far clip

    # --- Camera object ------------------------------------------------------
    cam_obj = bpy.data.objects.new(name="Player_Camera", object_data=cam_data)
    bpy.context.collection.objects.link(cam_obj)

    # --- Position & orientation ---------------------------------------------
    cam_obj.location       = (center_x, center_y, EYE_HEIGHT_M)
    # 90 deg around X -> camera looks along +Y (Blender default -Z tilted).
    cam_obj.rotation_euler = (math.radians(90), 0.0, 0.0)

    # --- Set as the active scene camera ------------------------------------
    bpy.context.scene.camera = cam_obj

    log(
        f"Player_Camera placed at "
        f"({center_x:.3f}, {center_y:.3f}, {EYE_HEIGHT_M}) "
        f"| Rotation: (90 deg, 0, 0) | Set as active scene camera."
    )
    return cam_obj


# =============================================================================
# STEP 6 - Save .blend File
# =============================================================================

def save_blend(output_path: str) -> None:
    """
    Persist the fully configured scene to disk as a .blend file.

    Uses compress=True to apply zlib compression, which meaningfully reduces
    file size for scenes with large vertex-color meshes.

    Args:
        output_path: Destination file path for the .blend file.
    """
    log(f"Saving .blend file to: {output_path} ...")

    bpy.ops.wm.save_as_mainfile(filepath=output_path, compress=True)

    log("Scene saved successfully. Pipeline complete.")


# =============================================================================
# MAIN ENTRY POINT
# =============================================================================

def main() -> None:
    """
    Top-level orchestrator.  Calls each pipeline stage in order and logs
    progress.  Any uncaught exception will propagate to Blender's stderr.
    """
    log("=" * 60)
    log("2D Floor Plan -> 3D Walkable Scene Builder")
    log("=" * 60)

    # 1. Parse CLI arguments and clear the default scene.
    input_3mf, output_blend = parse_cli_args()
    clear_default_scene()

    # 2. Import the 3MF mesh and optimize its geometry.
    house_obj = import_3mf(input_3mf)
    apply_smooth_shading(house_obj)

    # 3. Create a PBR material driven by the mesh's vertex colors.
    build_vertex_color_material(house_obj)

    # 4. Set up Cycles + Nishita Sky for realistic daylight.
    setup_sky_and_lighting()

    # 5. Place the first-person camera at eye height inside the house.
    setup_first_person_camera(house_obj)

    # 6. Write the .blend file to disk.
    save_blend(output_blend)

    log("=" * 60)
    log("Done. Open the .blend file in Blender for an interactive walkthrough.")
    log("=" * 60)


if __name__ == "__main__":
    main()
