"""
build_walkable_scene.py
=======================
Blender Python pipeline script for converting a 2D-floor-plan-derived
3MF house mesh (generated by OpenSCAD) into a fully configured, walkable
Blender scene.

Usage (from the command line):
    blender -b -P build_walkable_scene.py -- house_model.3mf interactive_house.blend

Arguments after '--' are parsed by this script:
    argv[0]  ->  Path to the input .3mf file
    argv[1]  ->  Path for the output .blend file

Pipeline Steps:
    1. Scene Initialization   - Clear default objects, parse CLI args.
    2. Mesh Import            - Parse the .3mf natively (stdlib), write a
                                temp OBJ, import via wm.obj_import, then
                                bake per-face colors into a vertex color
                                attribute.
    3. Vertex Color Material  - PBR Principled BSDF driven by vertex colors.
    4. Sky & Lighting         - Cycles engine + Nishita Sky for daylight.
    5. First-Person Camera    - "Player_Camera" at eye-level inside the mesh.
    6. Save & Exit            - Write the .blend file and quit cleanly.

Note on Blender 5.2 compatibility:
    Blender 5.2 no longer bundles the io_scene_3mf add-on, so
    bpy.ops.import_mesh.threemf does not exist.  A .3mf file is a ZIP
    archive containing XML geometry (3D Manufacturing Format spec).  We
    parse it with stdlib zipfile + xml.etree.ElementTree, convert to a
    temporary .obj + .mtl, import with bpy.ops.wm.obj_import, and then
    bake the per-face material colors into a Blender vertex color layer.
"""

import sys
import math
import os
import tempfile
import zipfile
import xml.etree.ElementTree as ET
import bpy


# =============================================================================
# STEP 0 - Utility helpers
# =============================================================================

def log(msg: str) -> None:
    """Simple timestamped logger so progress is visible in the Blender console."""
    print(f"[build_walkable_scene] {msg}", flush=True)


def deselect_all() -> None:
    """Deselect every object in the scene."""
    bpy.ops.object.select_all(action='DESELECT')


def select_obj(obj: bpy.types.Object) -> None:
    """Select *obj* and make it the active object."""
    deselect_all()
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj


# =============================================================================
# STEP 1 - Scene Initialization
# =============================================================================

def parse_cli_args() -> tuple:
    """
    Parse the input .3mf and output .blend paths from the command line.

    Supports two invocation modes:

    1. Via Blender (canonical):
            blender -b -P build_walkable_scene.py -- house.3mf out.blend
       Blender inserts a '--' separator; we slice everything after it.

    2. Direct Python (development / bpy-pip):
            python build_walkable_scene.py house.3mf out.blend
       No '--' separator; we treat sys.argv[1] and sys.argv[2] directly.

    Returns:
        (input_3mf_path, output_blend_path) as a tuple of strings.
    """
    # --- Mode 1: Blender wrapper (has '--' separator) -----------------------
    if "--" in sys.argv:
        separator_index = sys.argv.index("--")
        script_args = sys.argv[separator_index + 1:]
        mode = "blender-wrapped"

    # --- Mode 2: Direct Python invocation (no '--') -------------------------
    else:
        # sys.argv[0] is the script name; [1] and [2] are the user args.
        script_args = sys.argv[1:]
        mode = "direct-python"

    if len(script_args) < 2:
        raise SystemExit(
            "ERROR: Expected 2 path arguments.\n\n"
            "  Via Blender :\n"
            "    blender -b -P build_walkable_scene.py -- "
            "house_model.3mf interactive_house.blend\n\n"
            "  Direct Python:\n"
            "    python build_walkable_scene.py "
            "house_model.3mf interactive_house.blend\n\n"
            f"Received ({mode}): {script_args}"
        )

    input_path  = script_args[0]
    output_path = script_args[1]
    log(f"Invocation mode : {mode}")
    log(f"Input  .3mf     : {input_path}")
    log(f"Output .blend   : {output_path}")
    return input_path, output_path


def clear_default_scene() -> None:
    """
    Remove every object that Blender places in a new scene by default
    (Cube, Camera, Light) so we start with a completely empty slate.
    Also purge orphaned data-blocks to keep the file clean.
    """
    log("Clearing default scene objects ...")

    # Iterate over a *copy* because we modify bpy.data.objects in-place.
    for obj in list(bpy.data.objects):
        bpy.data.objects.remove(obj, do_unlink=True)

    # Purge orphaned mesh, light, and camera data-blocks.
    for mesh in list(bpy.data.meshes):
        bpy.data.meshes.remove(mesh)
    for light in list(bpy.data.lights):
        bpy.data.lights.remove(light)
    for camera in list(bpy.data.cameras):
        bpy.data.cameras.remove(camera)

    log("Default scene cleared.")


# =============================================================================
# STEP 2 - Mesh Import & Geometry Optimization
# =============================================================================

# =============================================================================
# 3MF NATIVE PARSER  (stdlib only — no Blender add-on required)
# =============================================================================

# The 3MF spec defines geometry inside a ZIP archive.  The main model file
# is typically "3D/3dmodel.model" and uses the namespace:
_3MF_NS = "http://schemas.microsoft.com/3dmanufacturing/core/2015/02"


def _parse_3mf_to_obj(filepath: str, obj_path: str, mtl_path: str) -> None:
    """
    Parse a .3mf file and write an equivalent Wavefront OBJ + MTL pair.

    3MF geometry lives in a ZIP archive under "3D/3dmodel.model".
    Each <object> element contains:
        <vertices>  ->  <vertex x y z>  entries.
        <triangles> ->  <triangle v1 v2 v3 pid p1> entries.
    The optional 'pid' / 'p1' attributes reference a <basematerials>
    palette which stores the RGB colors assigned via OpenSCAD color().

    We convert each material in the palette to a named MTL entry, then
    write per-face 'usemtl' directives so that after import Blender gives
    each face the correct color.  We then bake those per-face material
    colors into a vertex color attribute.

    Args:
        filepath : Path to the source .3mf file.
        obj_path : Destination path for the .obj text file.
        mtl_path : Destination path for the .mtl text file.
    """
    log(f"Parsing .3mf with stdlib XML parser: {filepath}")

    mtl_filename = os.path.basename(mtl_path)

    with zipfile.ZipFile(filepath, 'r') as zf:
        # Locate the primary model file (spec default: "3D/3dmodel.model").
        model_entry = None
        for name in zf.namelist():
            if name.lower().endswith(".model"):
                model_entry = name
                break
        if model_entry is None:
            raise RuntimeError(
                f"No .model entry found inside '{filepath}'. "
                "Is this a valid .3mf file?"
            )
        log(f"Found model entry: {model_entry}")
        model_xml = zf.read(model_entry)

    root = ET.fromstring(model_xml)
    ns   = {'m': _3MF_NS}

    # --- Parse material palettes (basematerials) ----------------------------
    # Maps palette_id -> {material_index -> (r, g, b)}  (floats 0-1)
    palettes: dict[str, dict[int, tuple]] = {}
    for bm in root.findall('.//m:basematerials', ns):
        pid = bm.get('id', '0')
        colors: dict[int, tuple] = {}
        for idx, base in enumerate(bm.findall('m:base', ns)):
            raw = base.get('displaycolor', '#FFFFFF')
            # displaycolor is a CSS hex string: #RRGGBB or #RRGGBBAA
            raw = raw.lstrip('#')
            r = int(raw[0:2], 16) / 255.0
            g = int(raw[2:4], 16) / 255.0
            b = int(raw[4:6], 16) / 255.0
            colors[idx] = (r, g, b)
        palettes[pid] = colors
        log(f"Palette '{pid}': {len(colors)} color(s).")

    # --- Build MTL file from palette colors ----------------------------------
    # mat name: "mat_{pid}_{index}"  e.g. "mat_1_0"
    mat_entries: dict[str, tuple] = {}  # name -> (r, g, b)
    for pid, colors in palettes.items():
        for idx, rgb in colors.items():
            mat_name = f"mat_{pid}_{idx}"
            mat_entries[mat_name] = rgb

    # Fallback white material used when no palette reference is present.
    mat_entries['mat_default'] = (0.8, 0.8, 0.8)

    with open(mtl_path, 'w') as mf:
        mf.write(f"# Generated by build_walkable_scene.py\n")
        for mname, (r, g, b) in mat_entries.items():
            mf.write(f"\nnewmtl {mname}\n")
            mf.write(f"Ka {r:.6f} {g:.6f} {b:.6f}\n")   # ambient
            mf.write(f"Kd {r:.6f} {g:.6f} {b:.6f}\n")   # diffuse
            mf.write(f"Ks 0.1 0.1 0.1\n")                # specular
            mf.write(f"Ns 10.0\n")                        # shininess
            mf.write(f"d 1.0\n")                          # opacity

    log(f"MTL written: {mtl_path} ({len(mat_entries)} materials)")

    # --- Parse geometry and write OBJ ----------------------------------------
    with open(obj_path, 'w') as of:
        of.write(f"# Generated by build_walkable_scene.py\n")
        of.write(f"mtllib {mtl_filename}\n\n")

        global_vertex_offset = 0  # OBJ vertex indices are 1-based and global.

        for obj_el in root.findall('.//m:object', ns):
            obj_id   = obj_el.get('id', 'unknown')
            obj_name = obj_el.get('name', f'object_{obj_id}').replace(' ', '_')
            mesh_el  = obj_el.find('m:mesh', ns)
            if mesh_el is None:
                continue

            of.write(f"o {obj_name}\n")

            # --- Vertices ---
            verts_el = mesh_el.find('m:vertices', ns)
            vertices = []
            if verts_el is not None:
                for v in verts_el.findall('m:vertex', ns):
                    x, y, z = float(v.get('x', 0)), float(v.get('y', 0)), float(v.get('z', 0))
                    vertices.append((x, y, z))
                    of.write(f"v {x:.8f} {y:.8f} {z:.8f}\n")

            # --- Triangles --------------------------------------------------
            # Group consecutive triangles that share the same material together
            # so we minimise 'usemtl' line changes.
            tris_el = mesh_el.find('m:triangles', ns)
            if tris_el is None:
                global_vertex_offset += len(vertices)
                continue

            triangles = tris_el.findall('m:triangle', ns)

            # Determine per-triangle material name.
            current_mat  = None
            base_offset  = global_vertex_offset  # offset for this object's verts

            of.write(f"usemtl mat_default\n")  # prime with a default
            current_mat = 'mat_default'

            for tri in triangles:
                v1 = int(tri.get('v1')) + base_offset + 1  # OBJ is 1-indexed
                v2 = int(tri.get('v2')) + base_offset + 1
                v3 = int(tri.get('v3')) + base_offset + 1

                pid = tri.get('pid')
                p1  = tri.get('p1')
                if pid is not None and p1 is not None:
                    mat_name = f"mat_{pid}_{p1}"
                else:
                    mat_name = 'mat_default'

                if mat_name not in mat_entries:
                    mat_name = 'mat_default'

                if mat_name != current_mat:
                    of.write(f"usemtl {mat_name}\n")
                    current_mat = mat_name

                of.write(f"f {v1} {v2} {v3}\n")

            global_vertex_offset += len(vertices)
            of.write("\n")

    log(f"OBJ written: {obj_path} ({global_vertex_offset} vertices total)")


# (vertex color baking removed — colors are now set directly on Principled BSDF)


# Furniture keyword list
_FURNITURE_KEYWORDS = (
    'bed', 'sofa', 'table', 'counter', 'chair', 'wardrobe',
    'shelf', 'desk', 'toilet', 'sink', 'bathtub', 'couch',
)


# Hardcoded PBR palette — rich, vivid, architectural
# Linear-space RGB 0-1 values. Made significantly darker per user request.
COLOR_PALETTE = {
    # Furniture
    'bed':              (0.20, 0.02, 0.02),   # Even Darker Crimson
    'sofa':             (0.01, 0.03, 0.08),   # Almost Black Navy
    'couch':            (0.01, 0.03, 0.08),   # Almost Black Navy
    'table':            (0.05, 0.03, 0.01),   # Almost Black Walnut
    'counter':          (0.05, 0.10, 0.10),   # Very Dark Teal
    'chair':            (0.08, 0.05, 0.02),   # Almost Black Tan
    'wardrobe':         (0.05, 0.02, 0.01),   # Very Dark Mahogany
    'desk':             (0.08, 0.05, 0.02),   # Dark Oak
    'toilet':           (0.50, 0.50, 0.55),   # Grey Porcelain
    'bathtub':          (0.45, 0.50, 0.55),   # Grey White
    'sink':             (0.40, 0.45, 0.50),   # Grey Silver
    'shelf':            (0.15, 0.08, 0.03),   # Dark Beech
    # Structure
    'wall':             (0.15, 0.14, 0.12),   # Extremely Dark Grey/Brown
    'floor':            (0.15, 0.08, 0.04),   # Very Dark Wood Floor
    'ceiling':          (0.30, 0.30, 0.25),   # Grey Cream
    'door':             (0.10, 0.05, 0.02),   # Very Dark Oak Door
    'window':           (0.10, 0.15, 0.20),   # Very Dark Glass
    # Fallbacks
    'default_furniture':(0.08, 0.05, 0.02),   # Very Dark Generic Wood
    'default_house':    (0.15, 0.14, 0.12),   # Extremely Dark Grey/Brown
}


def _is_furniture(name: str) -> bool:
    """Return True if the object name looks like a furniture piece."""
    return any(kw in name.lower() for kw in _FURNITURE_KEYWORDS)


def _get_color_for_object(obj) -> tuple:
    """
    Determine the best RGB color for an object.
    Priority: name keyword match -> geometry bounding-box heuristic.
    """
    name  = obj.name.lower()

    # 1. Name keyword match
    for key, color in COLOR_PALETTE.items():
        if key.startswith('default_'):
            continue
        if key in name:
            return color

    # 2. Geometry heuristic: analyse bounding box
    wm    = obj.matrix_world
    verts = [wm @ v.co for v in obj.data.vertices]
    if verts:
        zs = [v.z for v in verts]
        xs = [v.x for v in verts]
        ys = [v.y for v in verts]
        z0, z1 = min(zs), max(zs)
        dx, dy, dz = max(xs)-min(xs), max(ys)-min(ys), z1-z0

        # Tall -> wall
        if dz > 3.0:
            if min(dx, dy) <= 0.7:
                return COLOR_PALETTE['wall']
            return COLOR_PALETTE['default_house']

        # Flat slab -> floor
        if dz <= 0.5:
            return COLOR_PALETTE['floor']

        # Floating above floor -> furniture
        if z0 > 0.35:
            if dz < 1.5 and max(dx, dy) > 5.0:
                return COLOR_PALETTE['sofa'] if dy < 3.5 else COLOR_PALETTE['table']
            if dz > 1.0 and min(dx, dy) > 4.0:
                return COLOR_PALETTE['bed']
            return COLOR_PALETTE['default_furniture']

    # Final fallback
    if _is_furniture(obj.name):
        return COLOR_PALETTE['default_furniture']
    return COLOR_PALETTE['default_house']


def import_mesh_file(filepath: str) -> list:
    """
    Import a .3mf or .stl house mesh file into Blender 5.2.
    No vertex color baking — colors are applied directly as PBR materials.
    """
    log(f"Importing mesh file: {filepath} ...")
    abs_path = os.path.abspath(filepath)
    ext = os.path.splitext(abs_path)[1].lower()
    pre_import_names = {o.name for o in bpy.data.objects}

    if ext == '.stl':
        if hasattr(bpy.ops.wm, 'stl_import'):
            bpy.ops.wm.stl_import(filepath=abs_path)
        else:
            bpy.ops.import_mesh.stl(filepath=abs_path)

    elif ext == '.3mf':
        tmp_dir  = tempfile.mkdtemp()
        obj_path = os.path.join(tmp_dir, 'house_temp.obj')
        mtl_path = os.path.join(tmp_dir, 'house_temp.mtl')
        _parse_3mf_to_obj(abs_path, obj_path, mtl_path)
        bpy.ops.wm.obj_import(filepath=obj_path, forward_axis='Y', up_axis='Z')
        try:
            os.remove(obj_path)
            os.remove(mtl_path)
            os.rmdir(tmp_dir)
        except OSError as e:
            log(f'WARNING: Could not remove temp files: {e}')
    else:
        raise RuntimeError(f'Unsupported format: {ext}')

    imported = [
        o for o in bpy.data.objects
        if o.name not in pre_import_names and o.type == 'MESH'
    ]
    if not imported:
        raise RuntimeError('No mesh objects were imported. Check the input file.')

    # Separate by loose parts so floor, walls, and furniture are distinct
    bpy.ops.object.select_all(action='DESELECT')
    for obj in imported:
        obj.select_set(True)
    bpy.context.view_layer.objects.active = imported[0]
    bpy.ops.mesh.separate(type='LOOSE')

    new_objects = [
        o for o in bpy.data.objects
        if o.name not in pre_import_names and o.type == 'MESH'
    ]
    
    log(f'Imported and separated into {len(new_objects)} mesh object(s).')
    return new_objects


def apply_smooth_shading(obj: bpy.types.Object) -> None:
    """
    Apply Shade Smooth to the mesh and add an Edge Split modifier.

    Why Edge Split instead of the old Auto Smooth mesh property?
    - Blender 4.1+ removed 'mesh.use_auto_smooth' from the mesh data API.
    - Edge Split with a 30-degree threshold is the cross-version compatible
      approach: it keeps 90-degree architectural wall corners crisp while
      smoothing curved surfaces like arches or furniture.

    Threshold: 30 degrees
        - Edges whose dihedral angle exceeds 30 deg are split (rendered hard).
        - Right-angle walls (90 deg) are well above the threshold -> hard.
        - Gentle curves (< 30 deg between faces) -> smooth shading.
    """
    log(f"Applying shade-smooth + Edge Split on '{obj.name}' ...")

    select_obj(obj)
    bpy.ops.object.shade_smooth()

    edge_split_mod = obj.modifiers.new(name="Edge_Split_Arch", type='EDGE_SPLIT')
    edge_split_mod.split_angle    = math.radians(30)
    edge_split_mod.use_edge_angle = True
    edge_split_mod.use_edge_sharp = False

    log(f"Shade smooth + Edge Split applied to '{obj.name}'.")


def apply_smooth_shading_all(objects: list) -> None:
    """Apply shade smooth + Edge Split to every object in the list."""
    for obj in objects:
        apply_smooth_shading(obj)


# =============================================================================
# STEP 3 - Vertex Color PBR Material Setup
# =============================================================================

def get_vertex_color_layer_name(obj: bpy.types.Object) -> str:
    """
    Retrieve the name of the active vertex color / color attribute layer
    on the mesh.

    API compatibility:
        Blender 3.2+  -> mesh.color_attributes  (preferred)
        Blender < 3.2 -> mesh.vertex_colors      (legacy)

    Returns:
        Name string of the active color layer, or 'Col' as a safe fallback.
    """
    mesh = obj.data

    # Modern Blender 3.2+ path.
    if hasattr(mesh, "color_attributes") and len(mesh.color_attributes) > 0:
        active_attr = mesh.color_attributes.active_color
        layer_name  = active_attr.name if active_attr else mesh.color_attributes[0].name
        log(f"Found color_attributes layer: '{layer_name}'")
        return layer_name

    # Legacy path (Blender < 3.2).
    if hasattr(mesh, "vertex_colors") and len(mesh.vertex_colors) > 0:
        layer_name = mesh.vertex_colors.active.name
        log(f"Found vertex_colors layer: '{layer_name}'")
        return layer_name

    log("WARNING: No vertex color layer found. Falling back to 'Col'.")
    return "Col"


def upgrade_material_to_pbr(mat: bpy.types.Material) -> None:
    """
    Take an existing material (imported from OBJ/MTL) and upgrade its
    node tree to a proper Principled BSDF, preserving its Base Color.
    """
    # Extract existing color from either BSDF or diffuse fallback
    rgb = (0.8, 0.8, 0.8)
    if mat.use_nodes:
        bsdf = mat.node_tree.nodes.get('Principled BSDF')
        if bsdf and 'Base Color' in bsdf.inputs:
            c = bsdf.inputs['Base Color'].default_value
            rgb = (c[0], c[1], c[2])
    else:
        c = mat.diffuse_color
        rgb = (c[0], c[1], c[2])

    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()

    bsdf = nodes.new('ShaderNodeBsdfPrincipled')
    out  = nodes.new('ShaderNodeOutputMaterial')
    bsdf.location = (0,   0)
    out.location  = (400, 0)

    bsdf.inputs['Base Color'].default_value = (rgb[0], rgb[1], rgb[2], 1.0)
    bsdf.inputs['Roughness'].default_value  = 0.65
    bsdf.inputs['Metallic'].default_value   = 0.0

    spec_key = 'Specular IOR Level' if 'Specular IOR Level' in bsdf.inputs else 'Specular'
    if spec_key in bsdf.inputs:
        bsdf.inputs[spec_key].default_value = 0.15

    links.new(bsdf.outputs['BSDF'], out.inputs['Surface'])
    mat.diffuse_color = (rgb[0], rgb[1], rgb[2], 1.0)


def build_pbr_material(obj: bpy.types.Object) -> None:
    """Fallback for objects with no materials (e.g. STL)."""
    rgb = _get_color_for_object(obj)
    
    obj.data.materials.clear()

    if rgb == COLOR_PALETTE['wall'] or rgb == COLOR_PALETTE['default_house']:
        rgb_outer = rgb
        rgb_inner = (rgb[0] * 0.75, rgb[1] * 0.75, rgb[2] * 0.75)  # Darker inner walls
        
        mat_outer = bpy.data.materials.new(name=f"Mat_{obj.name}_Outer")
        mat_inner = bpy.data.materials.new(name=f"Mat_{obj.name}_Inner")
        
        for mat, c in [(mat_outer, rgb_outer), (mat_inner, rgb_inner)]:
            mat.use_nodes = True
            mat.diffuse_color = (c[0], c[1], c[2], 1.0)
            upgrade_material_to_pbr(mat)
            mat.node_tree.nodes['Principled BSDF'].inputs['Base Color'].default_value = (c[0], c[1], c[2], 1.0)
            obj.data.materials.append(mat)
            
        # Determine inner/outer faces based on bounding box
        verts = obj.data.vertices
        xs = [v.co.x for v in verts]
        ys = [v.co.y for v in verts]
        if xs and ys:
            min_x, max_x = min(xs), max(xs)
            min_y, max_y = min(ys), max(ys)
            margin = 0.1
            
            for poly in obj.data.polygons:
                nx, ny, nz = poly.normal.x, poly.normal.y, poly.normal.z
                cx, cy = poly.center.x, poly.center.y
                
                is_outer = False
                if abs(nz) < 0.1:  # Vertical face
                    if nx > 0.5 and cx >= max_x - margin: is_outer = True
                    elif nx < -0.5 and cx <= min_x + margin: is_outer = True
                    elif ny > 0.5 and cy >= max_y - margin: is_outer = True
                    elif ny < -0.5 and cy <= min_y + margin: is_outer = True
                
                poly.material_index = 0 if is_outer else 1
                
        obj.color = (rgb_outer[0], rgb_outer[1], rgb_outer[2], 1.0)

    else:
        mat = bpy.data.materials.new(name=f"Mat_{obj.name}")
        mat.use_nodes = True
        mat.diffuse_color = (rgb[0], rgb[1], rgb[2], 1.0)
        upgrade_material_to_pbr(mat)
        mat.node_tree.nodes['Principled BSDF'].inputs['Base Color'].default_value = (rgb[0], rgb[1], rgb[2], 1.0)
        obj.data.materials.append(mat)
        obj.color = (rgb[0], rgb[1], rgb[2], 1.0)


def build_materials_for_all(objects: list) -> None:
    """Build or upgrade PBR materials for all imported objects."""
    log("Upgrading materials to PBR ...")
    upgraded = set()

    for obj in objects:
        mats = obj.data.materials
        # If no materials, or if the only material is the fallback "mat_default"
        if not mats or (len(mats) == 1 and mats[0].name.startswith('mat_default')):
            build_pbr_material(obj)
        else:
            for mat in mats:
                if mat is None:
                    continue
                if mat.name not in upgraded:
                    upgrade_material_to_pbr(mat)
                    upgraded.add(mat.name)
            
            # Set viewport object color to the first material's color
            if mats[0]:
                obj.color = mats[0].diffuse_color

    log(f"Upgraded {len(upgraded)} unique material(s) across {len(objects)} object(s).")


# =============================================================================
# STEP 4 - Realistic Lighting & Sky
# =============================================================================

def setup_sky_and_lighting() -> None:
    """
    Switch the render engine to Cycles and add a Nishita Sky Texture as
    the World environment for physically-based outdoor daylight.

    Nishita Sky parameters used:
        sun_elevation  = 45 deg  -> mid-morning sun angle, good for shadows.
        sun_rotation   = 0 rad   -> sun located along the +Y axis.
        altitude       = 0 m     -> observer at sea level.
        air_density    = 1.0     -> standard clear atmosphere.
        dust_density   = 1.0     -> normal dust load.
        ozone_density  = 1.0     -> normal ozone layer.

    Cycles sample counts:
        128 samples (final) / 32 samples (preview) - good quality / speed
        balance for interactive use and quick test renders.
    """
    log("Setting up render engine and sky ...")

    scene = bpy.context.scene  # define scene first

    # Prefer EEVEE_NEXT (fast, real-time material colors); fall back to CYCLES.
    for engine in ('BLENDER_EEVEE_NEXT', 'BLENDER_EEVEE', 'CYCLES'):
        try:
            scene.render.engine = engine
            log(f"Render engine set to: {engine}")
            break
        except Exception:
            continue

    if scene.render.engine == 'CYCLES':
        scene.cycles.samples = 128
        scene.cycles.preview_samples = 32

    # Configure all open 3D Viewports to show Material Preview shading so
    # colors are visible the instant the .blend file is opened.
    for screen in bpy.data.screens:
        for area in screen.areas:
            if area.type == 'VIEW_3D':
                for space in area.spaces:
                    if space.type == 'VIEW_3D':
                        space.shading.type = 'MATERIAL'   # Material Preview mode
                        space.shading.use_scene_lights = True
                        space.shading.use_scene_world   = True
                        # In Solid mode, show material color instead of default grey
                        space.shading.color_type = 'MATERIAL'

    # --- World / sky node graph ---------------------------------------------
    world = bpy.data.worlds.new("Sky_World")
    scene.world = world
    world.use_nodes = True

    w_nodes = world.node_tree.nodes
    w_links = world.node_tree.links
    w_nodes.clear()

    # Background node controls overall sky brightness.
    bg_node = w_nodes.new(type='ShaderNodeBackground')
    bg_node.location = (300, 300)
    bg_node.inputs["Strength"].default_value = 1.0

    # Nishita physically-based sky texture.
    # NOTE: In Blender 5.x the sky_type enum was reorganised.
    # 'NISHITA' was split into 'SINGLE_SCATTERING' and 'MULTIPLE_SCATTERING'.
    # 'MULTIPLE_SCATTERING' is the high-quality equivalent of the old Nishita.
    sky_node = w_nodes.new(type='ShaderNodeTexSky')
    sky_node.location = (-100, 300)

    # Determine the correct sky type for this Blender version.
    sky_enum_values = sky_node.bl_rna.properties['sky_type'].enum_items.keys()
    if 'NISHITA' in sky_enum_values:
        # Blender 3.x / 4.x
        sky_node.sky_type = 'NISHITA'
        sky_node.sun_elevation  = math.radians(45)   # 45 degrees above horizon
        sky_node.sun_rotation   = 0.0                # Azimuth in radians
        sky_node.altitude       = 0.0
        sky_node.air_density    = 1.0
        sky_node.dust_density   = 1.0
        sky_node.ozone_density  = 1.0
        log("Sky type: NISHITA (Blender 3.x/4.x)")
    elif 'MULTIPLE_SCATTERING' in sky_enum_values:
        # Blender 5.x — NISHITA was renamed to MULTIPLE_SCATTERING
        sky_node.sky_type = 'MULTIPLE_SCATTERING'
        # sun_elevation and sun_rotation are still available in 5.x.
        if hasattr(sky_node, 'sun_elevation'):
            sky_node.sun_elevation = math.radians(45)
        if hasattr(sky_node, 'sun_rotation'):
            sky_node.sun_rotation  = 0.0
        log("Sky type: MULTIPLE_SCATTERING (Blender 5.x equivalent of Nishita)")
    else:
        # Last-resort fallback: pick whatever the first available type is.
        first_type = list(sky_enum_values)[0]
        sky_node.sky_type = first_type
        log(f"WARNING: Neither NISHITA nor MULTIPLE_SCATTERING found. "
            f"Using '{first_type}' as fallback sky type.")

    # World Output.
    world_output = w_nodes.new(type='ShaderNodeOutputWorld')
    world_output.location = (600, 300)

    # Link: Sky -> Background -> World Output.
    w_links.new(sky_node.outputs["Color"],       bg_node.inputs["Color"])
    w_links.new(bg_node.outputs["Background"],   world_output.inputs["Surface"])

    log("Cycles engine + Nishita Sky (45 deg sun elevation) configured.")


# =============================================================================
# STEP 4b - Per-Room Lighting
# =============================================================================

def add_interior_lighting(objects: list) -> None:
    """
    Add interior point lights to illuminate the scene from within.

    Strategy:
        1. Compute the bounding box of the entire scene.
        2. Place one "Sun" area light above the model for exterior fill.
        3. Walk through every object; if it looks like a ceiling/floor slab
           (very flat), place a point light at its centroid to act as an
           interior room light.
        4. Add a warm fill light slightly off-center for visual warmth.

    Args:
        objects: List of all imported mesh objects.
    """
    log("Adding interior and ambient lighting ...")

    scene = bpy.context.scene

    # --- Collect overall scene bounds ----------------------------------------
    all_xs, all_ys, all_zs = [], [], []
    for obj in objects:
        wm = obj.matrix_world
        for v in obj.data.vertices:
            co = wm @ v.co
            all_xs.append(co.x)
            all_ys.append(co.y)
            all_zs.append(co.z)

    if not all_xs:
        log("WARNING: No geometry found; skipping interior lighting.")
        return

    cx = (min(all_xs) + max(all_xs)) / 2.0
    cy = (min(all_ys) + max(all_ys)) / 2.0
    top_z = max(all_zs)

    # --- Sun lamp (overhead exterior fill) -----------------------------------
    sun_data = bpy.data.lights.new(name="Sun_Fill", type='SUN')
    sun_data.energy = 1.0   # Reduced from 3.0 to prevent overexposure
    sun_data.color  = (1.0, 0.97, 0.9)   # slightly warm white
    sun_data.angle  = math.radians(5)    # small angular diameter = harder shadows
    sun_obj = bpy.data.objects.new(name="Sun_Fill", object_data=sun_data)
    bpy.context.collection.objects.link(sun_obj)
    sun_obj.location       = (cx, cy, top_z + 20.0)
    sun_obj.rotation_euler = (math.radians(60), 0.0, math.radians(30))
    log(f"Sun lamp added at ({cx:.2f}, {cy:.2f}, {top_z + 20.0:.2f}).")

    # --- Central warm fill point light ---------------------------------------
    fill_data = bpy.data.lights.new(name="Interior_Fill", type='POINT')
    fill_data.energy = 150.0  # Reduced from 500.0 to prevent washing out colors
    fill_data.color  = (1.0, 0.9, 0.75)   # warm incandescent tone
    fill_data.shadow_soft_size = 2.0
    fill_obj = bpy.data.objects.new(name="Interior_Fill", object_data=fill_data)
    bpy.context.collection.objects.link(fill_obj)
    fill_obj.location = (cx, cy, top_z * 0.85)
    log(f"Interior fill light at Z={top_z * 0.85:.2f}.")

    # --- Per-object accent lights for furniture ------------------------------
    light_count = 0
    for obj in objects:
        if not _is_furniture(obj.name):
            continue
        wm = obj.matrix_world
        verts = [wm @ v.co for v in obj.data.vertices]
        if not verts:
            continue
        obj_cx = sum(v.x for v in verts) / len(verts)
        obj_cy = sum(v.y for v in verts) / len(verts)
        obj_cz = max(v.z for v in verts) + 1.5   # 1.5 units above furniture top

        accent_data = bpy.data.lights.new(
            name=f"Accent_{obj.name}", type='POINT'
        )
        accent_data.energy = 80.0
        accent_data.color  = (1.0, 0.95, 0.85)
        accent_data.shadow_soft_size = 0.5
        accent_obj = bpy.data.objects.new(
            name=f"Accent_{obj.name}", object_data=accent_data
        )
        bpy.context.collection.objects.link(accent_obj)
        accent_obj.location = (obj_cx, obj_cy, obj_cz)
        light_count += 1

    log(f"Added {light_count} furniture accent light(s).")


# =============================================================================
# STEP 5 - First-Person Camera Setup
# =============================================================================

def compute_mesh_center_xy(obj: bpy.types.Object) -> tuple:
    """
    Compute the horizontal (X, Y) center of the house mesh from its
    world-space bounding box.

    The object's world matrix is applied to every vertex so the result
    is correct even if the mesh has been translated, rotated, or scaled.

    Args:
        obj: The house mesh object.

    Returns:
        (center_x, center_y) as floats in world-space metres.
    """
    world_matrix = obj.matrix_world
    mesh_data    = obj.data

    # Transform every vertex to world space.
    global_verts = [world_matrix @ v.co for v in mesh_data.vertices]

    if not global_verts:
        raise RuntimeError(
            "House mesh has no vertices - cannot compute bounding box center."
        )

    xs = [v.x for v in global_verts]
    ys = [v.y for v in global_verts]

    center_x = (min(xs) + max(xs)) / 2.0
    center_y = (min(ys) + max(ys)) / 2.0

    log(f"Mesh bounding-box XY center: ({center_x:.4f}, {center_y:.4f})")
    return center_x, center_y


def setup_first_person_camera(objects: list) -> bpy.types.Object:
    """
    Create a 'Player_Camera' positioned at the center of the house at
    standard human eye height (1.6 m) and oriented to look forward.

    Camera specifications:
        Location    : (center_x, center_y, 1.6)
        Rotation    : (90 deg, 0, 0) in XYZ Euler
                      -> camera forward vector = +Y.
        Focal length: 60 mm  -> natural perspective.
        Clip Start  : 0.05 m -> prevents z-fighting with thin walls.
        Clip End    : 500 m  -> sufficient for any domestic floor plan.

    Args:
        objects: List of all imported mesh objects (used to compute XY center).

    Returns:
        The created camera object.
    """
    log("Creating first-person Player_Camera ...")

    # Aggregate bounding box across all objects.
    all_xs, all_ys = [], []
    for obj in objects:
        wm = obj.matrix_world
        for v in obj.data.vertices:
            co = wm @ v.co
            all_xs.append(co.x)
            all_ys.append(co.y)

    if not all_xs:
        raise RuntimeError("No geometry found — cannot place camera.")

    center_x = (min(all_xs) + max(all_xs)) / 2.0
    center_y = (min(all_ys) + max(all_ys)) / 2.0
    log(f"Scene XY center: ({center_x:.4f}, {center_y:.4f})")

    EYE_HEIGHT_M = 1.6

    cam_data            = bpy.data.cameras.new(name="Player_Camera_Data")
    cam_data.lens       = 60.0
    cam_data.clip_start = 0.05
    cam_data.clip_end   = 500.0

    cam_obj = bpy.data.objects.new(name="Player_Camera", object_data=cam_data)
    bpy.context.collection.objects.link(cam_obj)

    cam_obj.location       = (center_x, center_y, EYE_HEIGHT_M)
    cam_obj.rotation_euler = (math.radians(90), 0.0, 0.0)
    bpy.context.scene.camera = cam_obj

    log(
        f"Player_Camera placed at ({center_x:.3f}, {center_y:.3f}, {EYE_HEIGHT_M}) "
        "| Rotation: (90 deg, 0, 0) | Set as active scene camera."
    )
    return cam_obj


# =============================================================================
# STEP 6 - Save .blend File
# =============================================================================

def save_blend(output_path: str) -> None:
    """
    Persist the fully configured scene to disk as a .blend file.

    Uses compress=True to apply zlib compression, which meaningfully reduces
    file size for scenes with large vertex-color meshes.

    Args:
        output_path: Destination file path for the .blend file.
    """
    log(f"Saving .blend file to: {output_path} ...")

    bpy.ops.wm.save_as_mainfile(filepath=output_path, compress=True)

    log("Scene saved successfully. Pipeline complete.")


def export_glb(output_path: str) -> None:
    """
    Export the constructed scene as a Web-ready .glb file.
    """
    glb_path = output_path.replace('.blend', '.glb')
    if not glb_path.endswith('.glb'):
        glb_path += '.glb'
        
    log(f"Exporting Web-ready .glb file to: {glb_path} ...")
    
    # We are removing the try/except block so if it fails, it will print the EXACT error!
    bpy.ops.export_scene.gltf(
        filepath=glb_path,
        export_format='GLB'
    )
    log("GLB export successful.")

# =============================================================================
# MAIN ENTRY POINT
# =============================================================================



def swap_furniture_with_assets() -> None:
    """Reads furniture.json and spawns high-quality GLB assets at precise AI coordinates."""
    log("Spawning high-quality furniture from JSON coordinates...")
    
    import json
    import math
    import mathutils
    import os
    
    script_dir = os.path.dirname(os.path.abspath(__file__))
    assets_dir = os.path.join(script_dir, "assets")
    json_path = os.path.join(script_dir, "furniture.json")
    
    if not os.path.exists(json_path):
        log("No furniture.json found. Skipping furniture placement.")
        return
        
    with open(json_path, "r") as f:
        furniture_list = json.load(f)
        
    for item in furniture_list:
        ftype = item.get("type", "").lower()
        x = item.get("x", 0)
        y = item.get("y", 0)
        rot_deg = item.get("rot", 0)
        
        asset_file = None
        if "bed" in ftype: asset_file = "bed.glb"
        elif "sofa" in ftype: asset_file = "sofa.glb"
        elif "table" in ftype: asset_file = "table.glb"
        elif "counter" in ftype: asset_file = "counter.glb"
        elif "cabinet" in ftype: asset_file = "cabinet.glb" # Added support for cabinet!
        
        if asset_file:
            asset_path = os.path.join(assets_dir, asset_file)
            if os.path.exists(asset_path):
                # Target dimensions (in feet, matching OpenSCAD AI logic)
                target_w, target_d = 0.0, 0.0
                if asset_file == "bed.glb": target_w, target_d = 6.5, 5.0
                elif asset_file == "sofa.glb": target_w, target_d = 7.0, 2.8
                elif asset_file == "table.glb": target_w, target_d = 5.0, 3.2
                elif asset_file == "counter.glb": 
                    target_w = item.get("w", 4.0)
                    target_d = item.get("d", 2.0)
                elif asset_file == "cabinet.glb":
                    target_w = item.get("w", 4.0)
                    target_d = item.get("d", 1.5)
                
                z0 = 0.4  # Floor height
                
                pre_import = set(bpy.context.scene.objects)
                bpy.ops.import_scene.gltf(filepath=asset_path)
                post_import = set(bpy.context.scene.objects)
                new_asset_parts = list(post_import - pre_import)
                
                root_obj = None
                for obj in new_asset_parts:
                    if obj.parent is None:
                        root_obj = obj
                        break
                        
                if root_obj:
                    # Apply rotation first
                    root_obj.rotation_euler = (0, 0, math.radians(rot_deg))
                    bpy.context.view_layer.update()
                    
                    # 1. Measure the current physical size of the asset
                    min_x = min_y = float('inf')
                    max_x = max_y = float('-inf')
                    for obj in new_asset_parts:
                        if obj.type == 'MESH':
                            for v in obj.bound_box:
                                v_world = obj.matrix_world @ mathutils.Vector(v)
                                min_x = min(min_x, v_world.x)
                                max_x = max(max_x, v_world.x)
                                min_y = min(min_y, v_world.y)
                                max_y = max(max_y, v_world.y)
                    
                    current_w = max(0.01, max_x - min_x)
                    current_d = max(0.01, max_y - min_y)
                    
                    # 2. Scale the asset so its bounding box EXACTLY matches the OpenSCAD target dimensions
                    scale_factor = max(target_w / current_w, target_d / current_d)
                    
                    # Prevent zero division / huge stretching if rotated internally
                    if abs((target_w / current_w) - (target_d / current_d)) > 1.0:
                         scale_factor = max(target_w / current_d, target_d / current_w)
                         
                    root_obj.scale = (scale_factor, scale_factor, scale_factor)
                    bpy.context.view_layer.update()
                    
                    # 3. Flawless Bounding Box Alignment!
                    # We recalculate the bounding box AFTER scaling
                    min_x = min_y = min_z = float('inf')
                    for obj in new_asset_parts:
                        if obj.type == 'MESH':
                            for v in obj.bound_box:
                                v_world = obj.matrix_world @ mathutils.Vector(v)
                                min_x = min(min_x, v_world.x)
                                min_y = min(min_y, v_world.y)
                                min_z = min(min_z, v_world.z)
                    
                    # We shift the asset so its absolute lowest X, Y, and Z bounds 
                    # perfectly align with the AI's targeted bottom-left corner!
                    # No matter where the GLB creator put the pivot point, this guarantees it won't go through walls!
                    root_obj.location.x += (x - min_x)
                    root_obj.location.y += (y - min_y)
                    root_obj.location.z += (z0 - min_z)
                    
    log("Furniture JSON placement complete!")

def main() -> None:
    """
    Top-level orchestrator.  Calls each pipeline stage in order and logs
    progress.  Any uncaught exception will propagate to Blender's stderr.
    """
    log("=" * 60)
    log("2D Floor Plan -> 3D Walkable Scene Builder")
    log("=" * 60)

    # 1. Parse CLI arguments and clear the default scene.
    input_3mf, output_blend = parse_cli_args()
    clear_default_scene()

    # 2. Import mesh (supports both .stl and .3mf).
    all_objects = import_mesh_file(input_3mf)

    # 3. Apply smooth shading + Edge Split to every object.
    apply_smooth_shading_all(all_objects)

    # 4. Build per-object PBR materials driven by vertex colors.
    build_materials_for_all(all_objects)

    # 4b. Add interior point lights + sun lamp.
    add_interior_lighting(all_objects)

    # 5. Set up Cycles + Nishita Sky for realistic daylight.
    setup_sky_and_lighting()

    # 6. Place the first-person camera at eye height inside the house.
    setup_first_person_camera(all_objects)

    # 6b. Spawn flawlessly aligned high-quality assets.
    swap_furniture_with_assets()

    # 7. Write the .blend file to disk.
    save_blend(output_blend)
    
    # 8. Export to .glb for web usage.
    export_glb(output_blend)

    log("=" * 60)
    log("Done. Open the .blend file in Blender for an interactive walkthrough.")
    log("=" * 60)


if __name__ == "__main__":
    main()
